title: Product
default_field: title
icon: 'far fa-file-alt'
hide: false
sections:
  main:
    title: admin_main
    fields:
      title:
        title: admin_title
        type: text
        size: '12'
      intro:
        title: Intro
        type: html
        size: '12'
      introImg:
        title: 'Intro Image'
        type: media_select
        size: 3/12
  menu:
    title: Menu
    fields:
      menu_item_title:
        title: Title
        type: text
        size: 3/12
      menu_item_url:
        title: Url
        type: text
        size: 3/12
      menu_item_order:
        title: Order
        type: text
        size: 3/12
      menu_item_target:
        title: Target
        type: select
        options: { _self: _self, _blank: _blank, _parent: _parent, _top: _top }
        size: 3/12
  seo:
    title: Seo
    fields:
      description:
        title: Description
        type: textarea
        size: '12'
